[profile.default]
solc_version = '0.8.27'
evm_version = 'prague'
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/lib/contracts/libraries/=lib/uniswap-solidity-lib/contracts/libraries/",
    "@uniswap/v2-core/contracts/interfaces/=src/v2-core/interfaces/",
    "@uniswap/v2-core/contracts/libraries/=src/v2-core/libraries/",
]

fs_permissions = [
    { access = "write", path = "./deployments" },
    { access = "read", path = "./deployments" },
]

[rpc_endpoints]
local = "${LOCAL_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
